spring.application.name=vaultx-sp
# Required - full JDBC URL for Azure SQL Database
spring.datasource.url=jdbc:sqlserver://vaultx-server.database.windows.net:1433;database=vaultx_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

# Username (note: Azure uses username@servername format internally, but here you use just the user part)
spring.datasource.username=vaultx-serv-ad

# Password
spring.datasource.password=Vault_X_Kings_2025

# Driver class (required for SQL Server)
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Recommended for Azure SQL + Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
# or 'none' if you manage schema yourself
spring.jpa.hibernate.ddl-auto=validate
# helpful for debugging
spring.jpa.show-sql=true